### ISSUE TITLE
Можно секрет хранить тоже в захешированном виде, чтобы не было plaintext'а

### ISSUE THREAD

**Issue by coursar** [flashxxx2/tomcat#2]
https://github.com/flashxxx2/tomcat/blob/f657aaf432881cd5048fbe4ab761d31d89d395be/src/main/java/tech/itpark/proggerhub/service/AuthService.java#L67

**Comment by flashxxx2** [comment]
так я и храню его вроде в захешированном виде
![image](https://user-images.githubusercontent.com/44981216/116086568-9f2a5400-a6a8-11eb-87b3-9f3373c48e66.png)

**Comment by flashxxx2** [comment]
вот два запроса, которые я отправляю
![image](https://user-images.githubusercontent.com/44981216/116086712-c2550380-a6a8-11eb-889d-dd21e3fa4ccc.png)
